importing packages and libraries

In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [3]:
### reading patient dataset
df=pd.read_csv('Patient_Data.csv')

In [4]:
df.head()

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [61]:
### patient dataset info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [62]:
### checking missing values
df.isnull().sum()

PatientID         0
Name              0
Department        0
Doctor            0
BillAmount        2
ReceptionistID    0
CheckInTime       0
dtype: int64

In [63]:
#### fillling missing values with median 
#### missing value is float so filling median
df.fillna({'BillAmount':df.BillAmount.median()},inplace=True)

In [64]:
df.isnull().sum()

PatientID         0
Name              0
Department        0
Doctor            0
BillAmount        0
ReceptionistID    0
CheckInTime       0
dtype: int64

In [65]:
### checking duplicates
df.duplicated().sum()

np.int64(1)

In [66]:
df[df.duplicated()]

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [67]:
#### droping duplicates from dataset
df.drop_duplicates(inplace=True,ignore_index=True)

In [68]:
df.duplicated().sum()

np.int64(0)

In [69]:
#### droping ReceptionistID and checkInTime from dataset
df.drop(columns=['ReceptionistID','CheckInTime'],inplace=True)

In [70]:
df.head()

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John      5600.0
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose      5600.0

In [71]:
### calculating total bill department wise
total_bill_amount=df.groupby('Department')['BillAmount'].sum()

In [72]:
total_bill_amount

Department
Cardiology     11200.0
Dermatology     5600.0
Neurology       5600.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

In [73]:
#### reading billing dataset
df1=pd.read_csv('Billing_Data.csv')

In [74]:
df1

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [75]:
##### merging billing dataset and patient dataset on patientID
merged_df=pd.merge(df,df1,on='PatientID')

In [76]:
### after merging the dataset
merged_df

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,2000,3000
1,102,Bob,Neurology,Dr. John,5600.0,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.0,3000,3200
4,105,Eva,Dermatology,Dr. Rose,5600.0,1000,4000

In [5]:
### concatenating  additional dataframe that contains new patients details of current week 
new_patients=pd.DataFrame({
    'PatientID':[106,107],
    'Name':['John','Robin'],
    'Department':['Neurology','Cardiology'],
    'Doctor':['Dr.Smith','Dr.Lee'], 
    'BillAmount':[5400.0,6600.0]})

In [78]:
#### new_patients dataset 
new_patients

   PatientID   Name  Department    Doctor  BillAmount
0        106   John   Neurology  Dr.Smith      5400.0
1        107  Robin  Cardiology    Dr.Lee      6600.0

In [79]:
df.head()

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John      5600.0
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose      5600.0

In [80]:
### concatenates new patient data with old patient data
df_updated=pd.concat([df,new_patients],ignore_index=True)

In [81]:
#### after concatenates
df_updated

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John      5600.0
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose      5600.0
5        106     John    Neurology   Dr.Smith      5400.0
6        107    Robin   Cardiology     Dr.Lee      6600.0

In [82]:
##### concatenating an new billing category 
insurance=pd.DataFrame({
    'PatientID':[106,107],
    'InsuranceCovered':[2400.0,3000.0],
    'FinalAmount':[3000.0,3600.0]})

In [83]:
df1_updated=pd.concat([df1,insurance],ignore_index=True)

In [84]:
### after concatenates
df1_updated

   PatientID  InsuranceCovered  FinalAmount
0        101            2000.0       3000.0
1        102            1500.0       3500.0
2        103            2500.0       5000.0
3        104            3000.0       3200.0
4        105            1000.0       4000.0
5        106            2400.0       3000.0
6        107            3000.0       3600.0

In [85]:
### final patient and billing dataset
final_updated_dataset=pd.merge(df_updated,df1_updated,on='PatientID')

In [86]:
final_updated_dataset

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,2000.0,3000.0
1,102,Bob,Neurology,Dr. John,5600.0,1500.0,3500.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,2500.0,5000.0
3,104,David,Cardiology,Dr. Smith,6200.0,3000.0,3200.0
4,105,Eva,Dermatology,Dr. Rose,5600.0,1000.0,4000.0
5,106,John,Neurology,Dr.Smith,5400.0,2400.0,3000.0
6,107,Robin,Cardiology,Dr.Lee,6600.0,3000.0,3600.0